artifact_uri: file:///C:/Users/Mewari's/Desktop/Online Tracker/MLops_Dvc_Proj_Sample/iris_mlflow/446307263907031480/3dc1da120bad49c2bb82a106682fb9bc/artifacts
end_time: 1688848553809
entry_point_name: ''
experiment_id: '446307263907031480'
lifecycle_stage: active
run_id: 3dc1da120bad49c2bb82a106682fb9bc
run_name: overjoyed-bass-564
run_uuid: 3dc1da120bad49c2bb82a106682fb9bc
source_name: ''
source_type: 4
source_version: ''
start_time: 1688848548889
status: 3
tags: []
user_id: Mewari's
