artifact_location: file:///C:/Users/Mewari's/Desktop/Online Tracker/MLops_Dvc_Proj_Sample/iris_mlflow/446307263907031480
creation_time: 1688847457864
experiment_id: '446307263907031480'
last_update_time: 1688847457864
lifecycle_stage: active
name: iris_experiment
