artifact_location: file:///C:/Users/Mewari's/Desktop/Online Tracker/MLops_Dvc_Proj_Sample/iris_mlflow/0
creation_time: 1688847457814
experiment_id: '0'
last_update_time: 1688847457814
lifecycle_stage: active
name: Default
